package com.wleft.config;

import com.wleft.entity.Product;
import com.wleft.repository.ProductRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;
import java.util.List;
import java.util.ArrayList;

@Component
public class DataSeeder implements CommandLineRunner {

    private final ProductRepository productRepository;
    private final RestTemplate restTemplate;

    public DataSeeder(ProductRepository productRepository) {
        this.productRepository = productRepository;
        this.restTemplate = new RestTemplate();
    }

    @Override
    public void run(String... args) throws Exception {
        if (productRepository.count() == 0) {
            System.out.println("Database is empty. Seeding data from FakeStoreAPI...");
            seedData();
        } else {
            System.out.println("Database already has data. Skipping seed.");
        }
    }

    private void seedData() {
        String url = "https://fakestoreapi.com/products";
        try {
            // Need a wrapper DTO or basic mapping. Since fields mostly match, we can map to
            // a DTO first or use array.
            // FakeStore Product fields: id, title, price, description, category, image,
            // rating
            // Our Product fields: id, title, description, price, image, quantity

            ResponseEntity<FakeStoreProduct[]> response = restTemplate.getForEntity(url, FakeStoreProduct[].class);
            FakeStoreProduct[] fakeProducts = response.getBody();

            if (fakeProducts != null) {
                List<Product> productsToSave = new ArrayList<>();
                for (FakeStoreProduct fp : fakeProducts) {
                    Product product = new Product();
                    // We let ID be auto-generated by our DB, or use the one from API?
                    // Usually safer to let DB generate, but requirements say "Map to Product
                    // entity".
                    // I will ignore API ID and let Postgres generate new IDs to avoid
                    // conflicts/gaps
                    // unless strictly needed. But usually syncing ID is better for consistency if
                    // re-importing.
                    // Given simple requirements, auto-gen is fine.

                    product.setTitle(fp.getTitle());
                    product.setPrice(fp.getPrice());
                    product.setDescription(fp.getDescription());
                    product.setImage(fp.getImage());
                    product.setQuantity(10); // Default quantity

                    productsToSave.add(product);
                }
                productRepository.saveAll(productsToSave);
                System.out.println("Seeded " + productsToSave.size() + " products successfully.");
            }
        } catch (Exception e) {
            System.err.println("Failed to seed data: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Inner DTO helper
    static class FakeStoreProduct {
        private Long id;
        private String title;
        private Double price;
        private String description;
        private String category;
        private String image;

        // Getters and Setters
        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public Double getPrice() {
            return price;
        }

        public void setPrice(Double price) {
            this.price = price;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        public String getImage() {
            return image;
        }

        public void setImage(String image) {
            this.image = image;
        }
    }
}
